server:
  port: 8094
spring:
  application:
    name: sc-service2

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.80.132:8848
        metadata:
          user:
            name: ${spring.security.user.name}  # 向注册中心注册本服务端点访问认证信息。这里不是配置访问客户端端点的认证信息，是本服务的
            password: ${spring.security.user.password}
            # management.context-path= # 访问地址，如果不是默认的actuator则需要配置

      username: nacos # nacos1.2以上版本增加客户端认证，需要认证才能读取配置
      password: vfc2020!@#

  profiles:
    include:
      - application-commons.yml

  security:
    user: # http端点认证用户
      name: admin
      password: client2020#
management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露web方式访问的所有端点
    jmx:
      exposure:
        exclude: '*' # 关闭端点JMX访问方式
  endpoint:
    health:
      show-details: always